logging:
  level:
    org.springframework.security: DEBUG

spring:
  application:
    name: service-auth
  main:
    allow-bean-definition-overriding: true
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        serviceName: service-auth
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.17.0.2:3306/uaa?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&serverTimezone=GMT%2B8
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  servlet:
    context-path: /uaa
  port: 5000
