server:
  port: 8081

spring:
  application:
    name: gateway-server
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    consul:
      host: localhost
      port: 8500
      discovery:
        serviceName: gateway-server
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true
      routes:
        - id: consul-provider
          uri: lb://consul-provider
          predicates:
            - Path=/hi
#          filters:
#            - StripPrefix=1
#            - RequestTime=true

#logging:
#  level:
#    org.springframework.cloud.gateway: debug